Create linters file, index.html and style.css.
emmanuellmhango/my-portifolio pull request #1
Opened 2022-09-21 22:19 UTC by emmanuellmhango

Checking the linters file

2022-09-22 22:31 UTC, jerryowusu reviewed
Hi @emmanuellmhango  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] You have submitted a project  without the readme file. Please make sure you have a descriptive readme file. Kindly check [this link](https://github.com/microverseinc/readme-template/blob/master/README.md) for a template of the readme file 
- [x] Your pull request should have a short summary describing introduced changes in more detail.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-22 23:31 UTC, emmanuellmhango commented
Please see the new changes. I have added a readme file. again I have managed to correct some styling errors flagged by linters

2022-09-23 00:04 UTC, mgmediaweb requested changes
Hi @emmanuellmhango , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost2](https://user-images.githubusercontent.com/41912912/191870444-30dc27de-70ea-4bb8-b01c-f3628f215a8d.gif)

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 
- Good job following the design. ✔️ 
- Good job following the advice of the previous reviewer ✔️ 

## Required Changes ♻️

- Kindly, I suggest you create a more descriptive Pull Request, explaining the details of the job you are submitting

Kindly, I suggest you review the following points so that your site is more similar to the original design of Figma
![image](https://user-images.githubusercontent.com/41912912/191871278-9d821b0b-2590-43a2-be74-531b1d34b7f0.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 00:04 UTC, mgmediaweb commented on index.html
> +        <div class="logo">My Logo</div>
Kindly, I suggest you put your name in this section and since this is the main logo, by convention always use an "A" tag with a link to home

2022-09-23 00:04 UTC, mgmediaweb commented on index.html
> +        <div class="description">I’m a software developer! I can help you build a product , feature or website Look
I kindly suggest using a "P" tag in this section

2022-09-23 00:04 UTC, mgmediaweb commented on index.html
> +            <li><a href="#"><img src="images/peace.png" alt=""></a></li>
Kindly, I suggest you to improve the accessibility of your site, put descriptive alternative text to each image

2022-09-23 00:04 UTC, mgmediaweb commented on index.html
> +                <li><a href="">Contact</a></li>
Kindly, I suggest you put "#" on links that don't have any address defined

2022-09-23 00:04 UTC, mgmediaweb commented on css/style.css
> +  margin-top: 114px;
Kindly, I suggest you not to put fixed top margins, you use flexbox which is a very good thing, I recommend you to put a section height of 100vh and center everything

2022-09-23 17:00 UTC, frank1738 approved these changes
Hi @emmanuellmhango , 

Good work implementing the changes requested. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good Design👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:05 UTC, merged